import { LoaderCircle, RefreshCw, Search } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getApiError } from "../../api/axios";
import Pagination from "../../components/Pagination";
import { EmptyState, ErrorState, StatusBadge } from "../../components/ui";
import { superadminService, type ResourceFilters } from "../../services/superadminService";

type Resource = "users" | "admins" | "guides" | "categories" | "destinations" | "trips" | "bookings" | "payments" | "reviews" | "groups";
const labels: Record<Resource, string> = { users: "Users", admins: "Admins", guides: "Guides", categories: "Categories", destinations: "Destinations", trips: "Trips", bookings: "Bookings", payments: "Payments", reviews: "Reviews", groups: "Groups" };
const fields: Record<Resource, string[]> = {
  users: ["fullName", "email", "role", "status", "emailVerified", "createdAt"], admins: ["fullName", "email", "status", "verificationStatus", "createdAt"], guides: ["fullName", "email", "status", "verificationStatus", "createdAt"],
  categories: ["name", "status", "createdAt"], destinations: ["name", "status", "createdAt"], trips: ["title", "status", "createdAt"], bookings: ["id", "status", "paymentStatus", "createdAt"], payments: ["id", "status", "method", "amount", "createdAt"], reviews: ["id", "status", "tripId", "rating", "createdAt"], groups: ["id", "name", "status", "createdAt"],
};

export default function PlatformResourcePage({ resource }: { resource: Resource }) {
  const [rows, setRows] = useState<unknown[]>([]); const [page, setPage] = useState(0); const [pages, setPages] = useState(0); const [filters, setFilters] = useState<ResourceFilters>({}); const [applied, setApplied] = useState<ResourceFilters>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updating, setUpdating] = useState<number | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = { ...applied, page, size: 20 }; const response = resource === "users" || resource === "admins" || resource === "guides" ? await superadminService.users(resource, query) : await superadminService.resource(resource, query); setRows(response.data.data?.content ?? []); setPages(response.data.data?.totalPages ?? 0); } catch (e) { setError(getApiError(e).message); } finally { setLoading(false); } }, [applied, page, resource]);
  useEffect(() => { void load(); }, [load]);
  const value = (row: unknown, key: string) => typeof row === "object" && row !== null ? (row as Record<string, unknown>)[key] : undefined;
  const apply = (event: React.FormEvent) => { event.preventDefault(); setPage(0); setApplied(filters); };
  const updateStatus = async (id: number, action: "activate" | "suspend" | "deactivate") => { setUpdating(id); try { await superadminService.updateUserStatus(id, action); await load(); } catch (e) { setError(getApiError(e).message); } finally { setUpdating(null); } };
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-widest text-[#b31919]">Platform resource</p><h1 className="mt-1 font-display text-3xl font-bold">{labels[resource]}</h1><p className="mt-2 text-sm text-gray-500">Manage protected platform records and review their current status.</p></header>
    <form onSubmit={apply} className="rounded-2xl border border-[#e5ddd6] bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><label className="relative sm:col-span-2"><span className="sr-only">Keyword</span><Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" /><input value={filters.keyword ?? ""} onChange={(e) => setFilters({ ...filters, keyword: e.target.value })} placeholder="Search keyword" className="w-full rounded-lg border px-9 py-2.5 text-sm outline-none focus:border-[#b31919]" /></label><select value={filters.status ?? ""} onChange={(e) => setFilters({ ...filters, status: e.target.value })} className="rounded-lg border px-3 py-2.5 text-sm"><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select>{resource === "users" && <><select value={filters.role ?? ""} onChange={(e) => setFilters({ ...filters, role: e.target.value })} className="rounded-lg border px-3 py-2.5 text-sm"><option value="">All roles</option><option>USER</option><option>ADMIN</option><option>FREELANCE_GUIDE</option></select><select value={String(filters.emailVerified ?? "")} onChange={(e) => setFilters({ ...filters, emailVerified: e.target.value === "" ? "" : e.target.value === "true" })} className="rounded-lg border px-3 py-2.5 text-sm"><option value="">Any email status</option><option value="true">Email verified</option><option value="false">Email unverified</option></select></>}{resource === "bookings" && <select value={filters.paymentStatus ?? ""} onChange={(e) => setFilters({ ...filters, paymentStatus: e.target.value })} className="rounded-lg border px-3 py-2.5 text-sm"><option value="">All payment statuses</option><option>PAID</option><option>PENDING</option><option>FAILED</option><option>REFUNDED</option></select>}{resource === "payments" && <input value={filters.method ?? ""} onChange={(e) => setFilters({ ...filters, method: e.target.value })} placeholder="Payment method" className="rounded-lg border px-3 py-2.5 text-sm" />}{resource === "reviews" && <input value={filters.tripId ?? ""} onChange={(e) => setFilters({ ...filters, tripId: e.target.value })} placeholder="Trip ID" className="rounded-lg border px-3 py-2.5 text-sm" />}<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#b31919] px-4 py-2.5 text-sm font-bold text-white"><Search className="h-4 w-4" /> Apply</button><button type="button" onClick={() => { setFilters({}); setApplied({}); setPage(0); }} className="inline-flex items-center justify-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-bold"><RefreshCw className="h-4 w-4" /> Reset</button></div></form>
    {error ? <ErrorState message={error} onRetry={() => void load()} /> : loading ? <div className="grid min-h-52 place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-[#b31919]" /></div> : rows.length === 0 ? <EmptyState title={`No ${labels[resource].toLowerCase()} found`} description="Try changing the filters or check the backend data." /> : <><div className="overflow-x-auto rounded-2xl border border-[#e5ddd6] bg-white shadow-sm"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#faf7f4] text-xs uppercase tracking-wide text-gray-500"><tr>{fields[resource].map((field) => <th key={field} className="px-4 py-3 font-bold">{field.replace(/[A-Z]/g, (letter) => ` ${letter}`).replace(/^./, (letter) => letter.toUpperCase())}</th>)}{resource === "users" && <th className="px-4 py-3">Actions</th>}</tr></thead><tbody className="divide-y divide-[#eee8e3]">{rows.map((row, index) => { const id = Number(value(row, "id")); return <tr key={id || index} className="align-top hover:bg-[#fffaf7]">{fields[resource].map((field) => <td key={field} className="max-w-[240px] px-4 py-4"><Cell value={value(row, field)} field={field} /></td>)}{resource === "users" && <td className="px-4 py-4"><div className="flex flex-wrap gap-2">{(["activate", "suspend", "deactivate"] as const).map((action) => <button key={action} disabled={!id || updating === id} onClick={() => void updateStatus(id, action)} className="rounded-md border px-2 py-1 text-xs font-bold capitalize hover:border-[#b31919] hover:text-[#b31919] disabled:opacity-50">{updating === id ? <LoaderCircle className="h-3 w-3 animate-spin" /> : action}</button>)}</div></td>}</tr>; })}</tbody></table></div><Pagination page={page + 1} totalPages={pages} onPageChange={(next) => setPage(next - 1)} /></>}</div>;
}

function Cell({ value, field }: { value: unknown; field: string }) { if (field === "status" || field === "verificationStatus" || field === "paymentStatus") return <StatusBadge status={String(value ?? "-")} />; if (field === "emailVerified") return <span className={value ? "font-semibold text-emerald-700" : "text-gray-500"}>{value ? "Verified" : "Unverified"}</span>; if (field === "createdAt") { const date = new Date(String(value)); return <span>{Number.isNaN(date.getTime()) ? String(value ?? "-") : new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(date)}</span>; } return <span className="break-words">{value == null ? "-" : typeof value === "object" ? JSON.stringify(value) : String(value)}</span>; }
