import { CalendarRange, Clock3, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { getApiError } from "../../../api/axios";
import { guideService, type GuideProfile } from "../../../services/guideService";

export default function GuideAvailability() {
  const [profile, setProfile] = useState<GuideProfile | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { guideService.me().then((response) => setProfile(response.data.data ?? null)).catch((e) => setError(getApiError(e).message)).finally(() => setLoading(false)); }, []);
  const toggle = async () => { if (!profile) return; setSaving(true); setError(""); setNotice(""); try { const response = await guideService.setAvailability(!profile.availability); setProfile(response.data.data ?? profile); setNotice(`You are now ${response.data.data?.availability ? "available" : "unavailable"}.`); } catch (e) { setError(getApiError(e).message); } finally { setSaving(false); } };
  if (loading) return <div className="grid min-h-52 place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-[#b31919]" /></div>;
  return <div className="mx-auto max-w-3xl space-y-6"><section className="rounded-2xl border border-[#eae3dc] bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-[#b31919]">Booking visibility</p><h2 className="mt-2 font-display text-3xl font-bold">Availability</h2><p className="mt-3 text-sm leading-6 text-gray-500">Set whether admins and travelers can currently consider you for assignments.</p><div className="mt-7 flex items-center justify-between rounded-xl border border-[#e5ddd6] bg-[#fcfaf7] p-5"><div><p className="font-bold">{profile?.availability ? "Available" : "Unavailable"}</p><p className="mt-1 text-xs text-gray-500">{profile?.availability ? "Your approved profile is accepting assignments." : "Your profile remains visible, but you are not accepting assignments."}</p></div><button type="button" role="switch" aria-checked={profile?.availability} disabled={saving} onClick={() => void toggle()} className={`relative h-8 w-14 rounded-full ${profile?.availability ? "bg-[#b31919]" : "bg-gray-300"}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white transition-transform ${profile?.availability ? "left-7" : "left-1"}`} /></button></div>{error && <p role="alert" className="mt-5 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="mt-5 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-800">{notice}</p>}</section><section className="rounded-2xl border border-[#eae3dc] bg-white p-6 shadow-sm"><h2 className="font-display text-2xl font-bold">Scheduling support</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-dashed border-[#d8cec0] p-5"><CalendarRange className="h-6 w-6 text-[#b31919]" /><p className="mt-3 font-bold">Date ranges</p><p className="mt-2 text-sm leading-6 text-gray-500">The backend currently provides global availability only. Date-range availability is not supported yet.</p></div><div className="rounded-xl border border-dashed border-[#d8cec0] p-5"><Clock3 className="h-6 w-6 text-[#b31919]" /><p className="mt-3 font-bold">Available times</p><p className="mt-2 text-sm leading-6 text-gray-500">Time-slot availability is not supported by the current API contract.</p></div></div></section></div>;
}
