import { LoaderCircle, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { getApiError } from "../../../api/axios";
import { EmptyState, ErrorState } from "../../../components/ui";
import { guideService, type GuideProfile } from "../../../services/guideService";
import type { TripReview } from "../../../services/reviewService";

export default function Reviews() {
  const [profile, setProfile] = useState<GuideProfile | null>(null); const [reviews, setReviews] = useState<TripReview[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { guideService.me().then(async (response) => { const guide = response.data.data; setProfile(guide ?? null); if (guide) { const reviewResponse = await guideService.reviews(guide.id); setReviews(reviewResponse.data.data?.content ?? []); } }).catch((e) => setError(getApiError(e).message)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="grid min-h-52 place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-[#b31919]" /></div>;
  if (error) return <ErrorState message={error} />;
  const distribution = [5,4,3,2,1].map((rating) => ({ rating, count: reviews.filter((review) => review.rating === rating).length }));
  return <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="h-fit rounded-2xl border border-[#eae3dc] bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-[#b31919]">Published feedback</p><p className="mt-4 text-center font-display text-5xl font-bold">{Number(profile?.rating ?? 0).toFixed(1)}</p><p className="mt-1 text-center text-xs text-gray-500">{reviews.length} reviews</p><div className="mt-6 space-y-2">{distribution.map((row) => <div key={row.rating} className="flex items-center gap-2 text-xs"><span className="w-7">{row.rating}★</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-[#f3ede8]"><div className="h-full bg-[#b31919]" style={{ width: `${reviews.length ? row.count / reviews.length * 100 : 0}%` }} /></div><span>{row.count}</span></div>)}</div></aside><section><h2 className="font-display text-2xl font-bold">Traveler reviews</h2>{reviews.length === 0 ? <div className="mt-5"><EmptyState title="No published reviews yet" description="Reviews from trips assigned to you will appear after admin moderation." /></div> : <div className="mt-5 space-y-4">{reviews.map((review) => <article key={review.id} className="rounded-2xl border border-[#eae3dc] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{review.reviewer.name}</b><p className="mt-1 text-xs text-gray-500">{review.trip.title}</p></div><span className="flex">{[1,2,3,4,5].map((star) => <Star key={star} className={`h-4 w-4 ${star <= review.rating ? "fill-amber-400 text-amber-400" : "text-gray-300"}`} />)}</span></div><h3 className="mt-4 font-bold">{review.title}</h3><p className="mt-2 text-sm leading-6 text-[#675b52]">{review.comment}</p><p className="mt-3 text-xs text-gray-500">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(review.createdAt))}</p></article>)}</div>}</section></div>;
}
