import { HeartOff, LoaderCircle, MapPin, Star } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router";
import { getApiError } from "../api/axios";
import Pagination from "../components/Pagination";
import { Button, EmptyState, ErrorState } from "../components/ui";
import { mediaUrl } from "../services/destinationService";
import { favoriteService, type Favorite } from "../services/favoriteService";

export default function FavoritesPage() {
  const [rows, setRows] = useState<Favorite[]>([]); const [page, setPage] = useState(0); const [pages, setPages] = useState(0); const [sortBy, setSortBy] = useState("createdAt"); const [sortDir, setSortDir] = useState<"asc" | "desc">("desc"); const [loading, setLoading] = useState(true); const [removing, setRemoving] = useState<number | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await favoriteService.list({ page, size: 12, sortBy, sortDir }); setRows(response.data.data?.content ?? []); setPages(response.data.data?.totalPages ?? 0); } catch (requestError) { setError(getApiError(requestError).message); } finally { setLoading(false); } }, [page, sortBy, sortDir]); useEffect(() => { void load(); }, [load]);
  const remove = async (destinationId: number) => { setRemoving(destinationId); try { await favoriteService.remove(destinationId); await load(); } catch (requestError) { setError(getApiError(requestError).message); } finally { setRemoving(null); } };
  return <main className="min-h-screen bg-[#f6f1e9] px-5 py-10"><div className="mx-auto max-w-6xl"><header><p className="text-xs font-bold uppercase tracking-widest text-[#a62922]">Saved places</p><h1 className="mt-2 font-display text-4xl font-bold">Favorite Destinations</h1></header><div className="mt-6 flex flex-wrap gap-3 rounded-xl border bg-white p-4"><select value={sortBy} onChange={(e) => { setSortBy(e.target.value); setPage(0); }} className="rounded-lg border px-3 py-2 text-sm"><option value="createdAt">Date saved</option><option value="destination.name">Name</option><option value="destination.rating">Rating</option><option value="destination.estimatedCost">Estimated cost</option></select><select value={sortDir} onChange={(e) => { setSortDir(e.target.value as "asc" | "desc"); setPage(0); }} className="rounded-lg border px-3 py-2 text-sm"><option value="desc">Descending</option><option value="asc">Ascending</option></select></div>{error ? <div className="mt-7"><ErrorState message={error} onRetry={() => void load()} /></div> : loading ? <div className="grid min-h-52 place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-[#a62922]" /></div> : rows.length === 0 ? <div className="mt-7"><EmptyState title="No favorite destinations" description="Save destinations to find them here." /></div> : <><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{rows.map(({ id, destination }) => <article key={id} className="overflow-hidden rounded-2xl bg-white shadow-sm"><Link to={`/destinations/${destination.id}`} className="block h-48 bg-[#ded4ca]">{destination.coverImage && <img src={mediaUrl(destination.coverImage)} alt={destination.name} className="h-full w-full object-cover" />}</Link><div className="p-5"><p className="text-xs font-bold uppercase text-[#a62922]">{destination.categoryName}</p><h2 className="mt-2 font-display text-2xl font-bold">{destination.name}</h2><p className="mt-2 flex items-center gap-1 text-sm text-gray-500"><MapPin className="h-4 w-4" /> {destination.district}, {destination.province}</p><p className="mt-2 flex items-center gap-1 text-sm"><Star className="h-4 w-4 fill-amber-400 text-amber-400" /> {Number(destination.rating).toFixed(1)}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><b>NPR {Number(destination.estimatedCost).toLocaleString()}</b><Button type="button" variant="danger" loading={removing === destination.id} onClick={() => void remove(destination.id)}><HeartOff className="h-4 w-4" /> Remove</Button></div></div></article>)}</div><Pagination page={page + 1} totalPages={pages} onPageChange={(next) => setPage(next - 1)} /></>}</div></main>;
}
