import { ArrowLeft, ArrowRight, CalendarDays, LoaderCircle, Users } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router";
import { getApiError } from "../api/axios";
import { ErrorState } from "../components/ui";
import { travelPackageService, type TravelPackage } from "../services/travelPackageService";

export default function TravelPackageDetail() {
  const { id = "" } = useParams(); const [item, setItem] = useState<TravelPackage | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await travelPackageService.byId(Number(id)); setItem(response.data.data ?? null); } catch (requestError) { setError(getApiError(requestError).message); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <main className="grid min-h-[70vh] place-items-center bg-[#f6f1e9]"><LoaderCircle className="h-8 w-8 animate-spin text-[#a62922]" /></main>;
  if (error || !item) return <main className="min-h-[70vh] bg-[#f6f1e9] px-5 py-14"><div className="mx-auto max-w-3xl"><ErrorState message={error || "Travel package not found"} onRetry={() => void load()} /></div></main>;
  const bookable = item.status === "PUBLISHED" && (item.availableSeats ?? item.capacity) > 0;
  return <main className="min-h-screen bg-[#f6f1e9] px-5 py-10"><div className="mx-auto max-w-4xl"><Link to="/travel-packages" className="inline-flex items-center gap-2 text-sm font-semibold text-[#a62922]"><ArrowLeft className="h-4 w-4" /> All travel packages</Link><article className="mt-7 rounded-2xl border border-[#e0d7cf] bg-white p-7 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#a62922]">{item.difficulty}</p><h1 className="mt-2 font-display text-4xl font-bold">{item.title}</h1></div><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-700">{item.status}</span></div><p className="mt-6 whitespace-pre-line text-base leading-8 text-[#675b52]">{item.description}</p><div className="mt-7 grid gap-4 border-y border-[#eee7e1] py-5 sm:grid-cols-3"><Info icon={CalendarDays} label="Duration" value={`${item.duration} days`} /><Info icon={Users} label="Capacity" value={`${item.availableSeats ?? item.capacity} seats`} /><Info label="Difficulty" value={item.difficulty} /></div>{item.itinerary.length > 0 && <section className="mt-8"><h2 className="font-display text-2xl font-bold">Itinerary</h2><ol className="mt-4 space-y-3">{item.itinerary.map((day, index) => <li key={`${index}-${day}`} className="rounded-lg bg-[#fcfaf8] p-4 text-sm leading-6 text-[#675b52]"><b>Day {index + 1}</b><p className="mt-1">{day}</p></li>)}</ol></section>}<div className="mt-8 flex flex-col gap-5 border-t border-[#eee7e1] pt-6 sm:flex-row sm:items-center sm:justify-between"><div><span className="text-sm text-[#786d63]">Package price</span><strong className="block font-display text-3xl text-[#a62922]">NPR {Number(item.price).toLocaleString()}</strong></div>{bookable ? <Link to={`/checkout?tripId=${item.id}`} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#a62922] px-6 py-3 text-sm font-bold text-white">Book now <ArrowRight className="h-4 w-4" /></Link> : <button type="button" disabled className="cursor-not-allowed rounded-lg bg-gray-300 px-6 py-3 text-sm font-bold text-gray-600">Booking unavailable</button>}</div></article></div></main>;
}

function Info({ icon: Icon, label, value }: { icon?: typeof CalendarDays; label: string; value: string }) { return <div className="flex items-center gap-3">{Icon && <Icon className="h-5 w-5 text-[#a62922]" />}<div><p className="text-xs font-bold uppercase tracking-wide text-[#897b70]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div></div>; }
