import { Client, type IMessage } from "@stomp/stompjs";
import { Bell, CheckCheck, LoaderCircle } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router";
import { useAuth } from "../context/AuthContext";
import { chatSocketUrl } from "../services/chatService";
import { formatNotificationTimestamp, notificationPath, notificationService, type Notification } from "../services/notificationService";

export default function NotificationBell({ dark = false }: { dark?: boolean }) {
  const { token, userDTO } = useAuth(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const [notifications, setNotifications] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const [loading, setLoading] = useState(true); const containerRef = useRef<HTMLDivElement>(null);
  const load = useCallback(async () => { if (!token) return; setLoading(true); try { const [list, count] = await Promise.all([notificationService.list({ page: 0, size: 5 }), notificationService.unreadCount()]); setNotifications(list.data.data?.content ?? []); setUnread(count.data.data ?? 0); } finally { setLoading(false); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (!token) return; const client = new Client({ brokerURL: chatSocketUrl, connectHeaders: { Authorization: `Bearer ${token}` }, reconnectDelay: 5000, onConnect: () => { client.subscribe("/user/queue/notifications", (frame: IMessage) => { const notification = JSON.parse(frame.body) as Notification; setNotifications((current) => [notification, ...current.filter((item) => item.id !== notification.id)].slice(0, 5)); setUnread((current) => current + (notification.read ? 0 : 1)); }); } }); client.activate(); return () => { void client.deactivate(); }; }, [token]);
  useEffect(() => { const close = (event: MouseEvent) => { if (!containerRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  const openNotification = async (notification: Notification) => { if (!notification.read) { try { await notificationService.markRead(notification.id); setNotifications((current) => current.map((item) => item.id === notification.id ? { ...item, read: true } : item)); setUnread((current) => Math.max(0, current - 1)); } catch { /* Navigation remains available if read persistence fails. */ } } setOpen(false); navigate(notificationPath(notification, userDTO?.role)); };
  const markAll = async () => { await notificationService.markAllRead(); setNotifications((current) => current.map((item) => ({ ...item, read: true }))); setUnread(0); };
  if (!token) return null;
  return <div ref={containerRef} className="relative"><button type="button" onClick={() => setOpen((value) => !value)} className={`relative rounded-lg p-2 transition ${dark ? "text-gray-300 hover:bg-white/10 hover:text-white" : "text-gray-500 hover:bg-gray-100 hover:text-[#2c2520]"}`} aria-label={`${unread} unread notifications`} aria-expanded={open}><Bell className="h-5 w-5" />{unread > 0 && <span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-[#b31919] px-1 text-[10px] font-bold text-white">{unread > 99 ? "99+" : unread}</span>}</button>{open && <div className="absolute right-0 z-[70] mt-2 w-[min(92vw,360px)] overflow-hidden rounded-xl border border-[#e5ddd6] bg-white text-[#2c2520] shadow-xl"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-display text-lg font-bold">Notifications</h2><p className="text-xs text-gray-500">{unread} unread</p></div>{unread > 0 && <button type="button" onClick={() => void markAll()} className="inline-flex items-center gap-1 text-xs font-bold text-[#b31919]"><CheckCheck className="h-4 w-4" /> Read all</button>}</div>{loading ? <div className="grid h-32 place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-[#b31919]" /></div> : notifications.length === 0 ? <p className="p-8 text-center text-sm text-gray-500">No notifications yet.</p> : <div>{notifications.map((notification) => <button key={notification.id} type="button" onClick={() => void openNotification(notification)} className={`block w-full border-b px-4 py-3 text-left hover:bg-[#fcfaf8] ${notification.read ? "" : "bg-[#fff7f5]"}`}><div className="flex items-start gap-3">{!notification.read && <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-[#b31919]" />}<div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wide text-[#b31919]">{notification.type.replaceAll("_", " ")}</p><p className="mt-1 text-sm font-semibold">{notification.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-gray-500">{notification.message}</p><time className="mt-1 block text-[10px] text-gray-400">{formatNotificationTimestamp(notification.createdAt)}</time></div></div></button>)}</div>}<button type="button" onClick={() => { setOpen(false); navigate("/notifications"); }} className="w-full px-4 py-3 text-center text-xs font-bold text-[#b31919] hover:bg-[#fcfaf8]">View all notifications</button></div>}</div>;
}
