import { Eye, EyeOff, LoaderCircle, Star } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { getApiError } from "../../../api/axios";
import { EmptyState, ErrorState } from "../../../components/ui";
import { reviewService, type ReviewStatus, type TripReview } from "../../../services/reviewService";

export default function AdminReviews() {
  const [reviews, setReviews] = useState<TripReview[]>([]); const [status, setStatus] = useState<ReviewStatus | "">(""); const [loading, setLoading] = useState(true); const [actionId, setActionId] = useState<number | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await reviewService.admin({ status }); setReviews(response.data.data?.content ?? []); } catch (e) { setError(getApiError(e).message); } finally { setLoading(false); } }, [status]); useEffect(() => { void load(); }, [load]);
  const moderate = async (review: TripReview, action: "publish" | "hide") => { setActionId(review.id); setError(""); try { if (action === "publish") await reviewService.publish(review.id); else await reviewService.hide(review.id); setNotice(`Review ${action === "publish" ? "published" : "hidden"}.`); await load(); } catch (e) { setError(getApiError(e).message); } finally { setActionId(null); } };
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#b31919]">Trip feedback</p><h2 className="mt-1 font-display text-2xl font-bold">Review Moderation</h2><p className="mt-1 text-sm text-gray-500">The backend returns only reviews belonging to this admin's trips.</p></div><select value={status} onChange={(e) => setStatus(e.target.value as ReviewStatus | "")} className="rounded-lg border border-[#d8cec0] bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option value="PENDING">Pending</option><option value="PUBLISHED">Published</option><option value="HIDDEN">Hidden</option></select></div>{notice && <p className="mt-5 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-800">{notice}</p>}{error ? <div className="mt-6"><ErrorState message={error} onRetry={() => void load()} /></div> : loading ? <div className="grid min-h-48 place-items-center"><LoaderCircle className="h-8 w-8 animate-spin text-[#b31919]" /></div> : reviews.length === 0 ? <div className="mt-6"><EmptyState title="No reviews found" description="No reviews match the selected moderation status." /></div> : <div className="mt-6 space-y-4">{reviews.map((review) => <article key={review.id} className="rounded-2xl border border-[#eae3dc] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-semibold">{review.reviewer.name} <span className="font-normal text-gray-500">on {review.trip.title}</span></p><div className="mt-2 flex items-center gap-2"><span className="flex">{[1,2,3,4,5].map((star) => <Star key={star} className={`h-4 w-4 ${star <= review.rating ? "fill-amber-400 text-amber-400" : "text-gray-300"}`} />)}</span><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold">{review.status}</span></div></div><div className="flex gap-2"><button type="button" disabled={actionId === review.id} onClick={() => void moderate(review, "publish")} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-green-700 disabled:opacity-50"><Eye className="h-4 w-4" /> Publish</button><button type="button" disabled={actionId === review.id} onClick={() => void moderate(review, "hide")} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-gray-700 disabled:opacity-50"><EyeOff className="h-4 w-4" /> Hide</button></div></div><h3 className="mt-4 font-bold">{review.title}</h3><p className="mt-2 text-sm leading-6 text-[#675b52]">{review.comment}</p><p className="mt-3 text-xs text-gray-500">Submitted {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(review.createdAt))}</p></article>)}</div>}</div>;
}
